### ISSUE TITLE
Apparently wrong GetOrgType()

### ISSUE THREAD

**Issue by alessandromrc** [calamity-inc/MusinessBanager#10]
```lua
local function GetOrgType()
    -- Returns -1, 0, 1. None, CEO, MC. This will only work if you are the boss of the org
    return GetGlobalInt(GetOrgOffset() + 509)
end
```

Apparently the offset + 509 is wrong and needs to be updated, I've tried 510 and it seems to work but I'm not sure if it is actually correct... I deducted it from seeing other offsets going up by just one.

Also I hope you might look up into my improved AFK Money Loop which I'm going to update the offsets right now because I got it working again on the latest DLC.

**Comment by Sainan** [comment]
Fixed in 4b00c016890fc2f43fb780ccaed93e7ed59d0bae
