### ISSUE TITLE
Bunker "Refill" & "Trigger Production" don't work

### ISSUE THREAD

**Issue by Tweezs** [calamity-inc/MusinessBanager#3]
Musiness Banager BUNKER Refill & trigger production not work since new dlc

**Comment by Sainan** [comment]
Not sure what you're on about. Just purchased a bunker, entered it, and as soon as I enabled "Resupply", supplies went to 100%. Please make sure your copy of MusinessBanager is up-to-date and, in fact, the one that is maintained in this repository.
